default: &default
  adapter: postgresql
  encoding: unicode
  host: ec2-34-250-19-18.eu-west-1.compute.amazonaws.com
  pool: 5
  username: iiftkxqqzzmhty
  password: 7aa6e7d5c68cadd8b4aa233962700bbdfc205513d97cd965daed53fac6ff9f29

development: &development
  <<: *default
  database: d4n09124h6lb68

# The staging, preproduction and production dbs are only needed
# for running rake assets:precompile locally before deploying
staging:
  <<: *development

preproduction:
  <<: *development

production:
  <<: *development

test:
  <<: *default
  database: consul_test
